language: ruby
branches:
  only:
    - master
rvm:
  - 2.3.0
bundler_args: "--jobs=3 --retry=3 --without development:production --deployment"
cache: bundler

before_install:
  - gem update bundler

script:
  - ./build.sh
