# Site settings
title: CS3281/2 Thematic Systems Project
email: cs3281-staff@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Working on large-scale systems with real impact.
baseurl: "/cs3281" # the subpath of your site, e.g. /blog/
url: "http://nus-oss.github.io" # the base hostname & protocol for your site
exclude: [vendor, build.sh]

# Build settings
markdown: kramdown
highlighter: rouge
